### ISSUE TITLE
Custom logo delayed

### ISSUE THREAD

**Issue by subjekt-iv** [GetMetaMap/metamap-reactnative-plugin#80]
When I set out company custom logo for the SDK through the getmati dashboard preview module, the logo is correctly applied into our flow but it has a delay. The flow is first loaded and suddenly the logo appears, I guess is something to do with the asset's size

**Comment by AvoSukiasyan** [comment]
@subjekt-iv 
the logo is presented a little later because it is created from a URL and the generation takes a little time.
We didn't want to continue loading because of this and that's why in some cases it appears a second late. 
if this is important to you? I can open this question on our company channel and maybe we can come up with something.
